import fs from "node:fs";
import path from "node:path";

// Reports are generated by the Python agent into ../reports relative to this
// web app. Each file is named <YYYY-MM-DD>.md.
const REPORTS_DIR = path.join(process.cwd(), "..", "reports");

export type Category =
  | "Trade rumor"
  | "Firing/Drama"
  | "Signing/Move"
  | "Beef/Fight"
  | "Other";

export interface Story {
  rank: number;
  headline: string;
  category: Category;
  realStory: string;
  whyItPops: string;
  sourceLabel: string;
  sourceUrl: string;
  clipUrl: string;
}

export interface Report {
  date: string; // YYYY-MM-DD
  stories: Story[];
}

function normalizeCategory(raw: string): Category {
  const c = raw.toLowerCase();
  if (c.includes("trade")) return "Trade rumor";
  if (c.includes("fir") || c.includes("drama")) return "Firing/Drama";
  if (c.includes("sign") || c.includes("move")) return "Signing/Move";
  if (c.includes("beef") || c.includes("fight")) return "Beef/Fight";
  return "Other";
}

function field(block: string, label: string): string {
  // Matches a line like: - **Label:** value
  const re = new RegExp(`-\\s*\\*\\*${label}:\\*\\*\\s*([\\s\\S]*?)(?:\\n-\\s*\\*\\*|$)`);
  const m = block.match(re);
  return m ? m[1].trim() : "";
}

function parseStory(block: string): Story | null {
  // Block starts with "N. headline"
  const headMatch = block.match(/^(\d+)\.\s*(.+)/);
  if (!headMatch) return null;
  const rank = parseInt(headMatch[1], 10);
  const headline = headMatch[2].trim();

  const source = field(block, "Source");
  // Source is "<label> — <url>", but Gemini often emits the url as a markdown
  // link "[url](url)". Prefer the link target; fall back to a bare url.
  const linkMatch = source.match(/\[[^\]]*\]\((https?:\/\/[^)]+)\)/);
  const bareMatch = source.match(/https?:\/\/[^\s)\]]+/);
  const sourceUrl = linkMatch ? linkMatch[1] : bareMatch ? bareMatch[0] : "";
  const sourceLabel = source
    .replace(/\[[^\]]*\]\([^)]*\)/g, "") // strip the markdown link
    .replace(/https?:\/\/\S+/g, "") // strip any leftover bare url
    .replace(/[—–-]\s*$/, "")
    .trim();

  // Optional video-clip tweet/post for the story. "None" (or empty) = no clip.
  const clip = field(block, "Clip");
  const clipLink = clip.match(/\[[^\]]*\]\((https?:\/\/[^)]+)\)/);
  const clipBare = clip.match(/https?:\/\/[^\s)\]]+/);
  const clipUrl = clipLink ? clipLink[1] : clipBare ? clipBare[0] : "";

  return {
    rank,
    headline,
    category: normalizeCategory(field(block, "Category")),
    realStory: field(block, "The real story"),
    whyItPops: field(block, "Why it pops"),
    sourceLabel: sourceLabel || source,
    sourceUrl,
    clipUrl,
  };
}

export function parseReport(date: string, markdown: string): Report {
  // Split on the "## " story delimiters.
  const parts = markdown.split(/\n##\s+/).slice(1);
  const stories = parts
    .map(parseStory)
    .filter((s): s is Story => s !== null)
    .sort((a, b) => a.rank - b.rank);
  return { date, stories };
}

export function getReportDates(): string[] {
  if (!fs.existsSync(REPORTS_DIR)) return [];
  return fs
    .readdirSync(REPORTS_DIR)
    .filter((f) => /^\d{4}-\d{2}-\d{2}\.md$/.test(f))
    .map((f) => f.replace(/\.md$/, ""))
    .sort()
    .reverse(); // newest first
}

export function getReport(date: string): Report | null {
  const file = path.join(REPORTS_DIR, `${date}.md`);
  if (!fs.existsSync(file)) return null;
  return parseReport(date, fs.readFileSync(file, "utf8"));
}

export function getLatestReport(): Report | null {
  const dates = getReportDates();
  return dates.length ? getReport(dates[0]) : null;
}
